In [45]:
import re
import string
import time
from copy import deepcopy

In [46]:
import pandas as pd

In [47]:
df = pd.read_csv('dataset_tweet_sentiment_opini_film.csv')

In [48]:
df.head()

   Id Sentiment                                         Text Tweet
0   1  negative  Jelek filmnya... apalagi si ernest gak mutu bg...
1   2  negative  Film king Arthur ini film paling jelek dari se...
2   3  negative  @beexkuanlin Sepanjang film gwa berkata kasar ...
3   4  negative  Ane ga suka fast and furious..menurutku kok je...
4   5  negative  @baekhyun36 kan gua ga tau film nya, lu bilang...

In [50]:
df = df.drop(['Id'], axis=1)

In [51]:
df

    Sentiment                                         Text Tweet
0    negative  Jelek filmnya... apalagi si ernest gak mutu bg...
1    negative  Film king Arthur ini film paling jelek dari se...
2    negative  @beexkuanlin Sepanjang film gwa berkata kasar ...
3    negative  Ane ga suka fast and furious..menurutku kok je...
4    negative  @baekhyun36 kan gua ga tau film nya, lu bilang...
..        ...                                                ...
195  positive  Fargo juga adaptasi dari film yang cukup berha...
196  positive  637.000 waw ini sangat keren flm horor dng jum...
197  positive  @filmziarah film yang tenang dan menghanyutkan...
198  positive  Film yg amat menarik. Kisah cinta & kesetiaan ...
199  positive  Nntn @filmziarah , film bagus, ada kali 5 meni...

[200 rows x 2 columns]

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Sentiment   200 non-null    object
 1   Text Tweet  200 non-null    object
dtypes: object(2)
memory usage: 3.2+ KB

In [53]:
!pip install ekphrasis

Requirement already satisfied: ekphrasis in c:\users\user\anaconda3\lib\site-packages (0.5.4)
Requirement already satisfied: termcolor in c:\users\user\anaconda3\lib\site-packages (from ekphrasis) (2.3.0)
Requirement already satisfied: ujson in c:\users\user\anaconda3\lib\site-packages (from ekphrasis) (5.4.0)
Requirement already satisfied: colorama in c:\users\user\anaconda3\lib\site-packages (from ekphrasis) (0.4.6)
Requirement already satisfied: nltk in c:\users\user\anaconda3\lib\site-packages (from ekphrasis) (3.7)
Requirement already satisfied: numpy in c:\users\user\appdata\roaming\python\python310\site-packages (from ekphrasis) (1.24.3)
Requirement already satisfied: tqdm in c:\users\user\anaconda3\lib\site-packages (from ekphrasis) (4.64.1)
Requirement already satisfied: matplotlib in c:\users\user\anaconda3\lib\site-packages (from ekphrasis) (3.7.0)
Requirement already satisfied: ftfy in c:\users\user\anaconda3\lib\site-packages (from ekphrasis) (6.1.1)
Requirement already satisfied: wcwidth>=0.2.5 in c:\users\user\anaconda3\lib\site-packages (from ftfy->ekphrasis) (0.2.5)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->ekphrasis) (4.25.0)
Requirement already satisfied: cycler>=0.10 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->ekphrasis) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from matplotlib->ekphrasis) (9.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->ekphrasis) (22.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->ekphrasis) (3.0.9)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->ekphrasis) (1.0.5)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->ekphrasis) (1.4.4)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->ekphrasis) (2.8.2)
Requirement already satisfied: click in c:\users\user\anaconda3\lib\site-packages (from nltk->ekphrasis) (8.0.4)
Requirement already satisfied: joblib in c:\users\user\anaconda3\lib\site-packages (from nltk->ekphrasis) (1.1.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\user\anaconda3\lib\site-packages (from nltk->ekphrasis) (2022.7.9)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib->ekphrasis) (1.16.0)

In [54]:
from ekphrasis.classes.preprocessor import TextPreProcessor
from ekphrasis.classes.tokenizer import SocialTokenizer
from ekphrasis.dicts.emoticons import emoticons

text_processor = TextPreProcessor(
    # terms that will be normalized
    normalize=['email', 'percent', 'money', 'phone', 'user',
        'time', 'date', 'number'],
    # terms that will be annotated
    #annotate={"hashtag", "allcaps", "elongated", "repeated",'emphasis', 'censored'},
    annotate={"hashtag"},
    fix_html=True,  # fix HTML tokens
    
    # corpus from which the word statistics are going to be used 
    # for word segmentation 
    segmenter="twitter", 
    
    # corpus from which the word statistics are going to be used 
    # for spell correction
    corrector="twitter", 
    
    unpack_hashtags=True,  # perform word segmentation on hashtags
    unpack_contractions=True,  # Unpack contractions (can't -> can not)
    spell_correct_elong=False,  # spell correction for elongated words
    
    # select a tokenizer. You can use SocialTokenizer, or pass your own
    # the tokenizer, should take as input a string and return a list of tokens
    tokenizer=SocialTokenizer(lowercase=True).tokenize,
    
    # list of dictionaries, for replacing tokens extracted from the text,
    # with other expressions. You can pass more than one dictionaries.
    dicts=[emoticons]
)

Reading twitter - 1grams ...
Reading twitter - 2grams ...
Reading twitter - 1grams ...

In [55]:
# panggil ekphrasis

def bersih_data(text):
    return " ".join(text_processor.pre_process_doc(text))

In [56]:
# fungsi dari AMS 01-03. silakan cek bagaimana saya merubah menjadi fungsi

def non_ascii(text):
    return text.encode('ascii', 'replace').decode('ascii')

def remove_space_alzami(text):
    return " ".join(text.split())

def remove_emoji_alzami(text):
    return ' '.join(re.sub("([x#][A-Za-z0-9]+)"," ", text).split())

def remove_tab(text):
    return text.replace('\\t'," ").replace('\\n'," ").replace('\\u'," ").replace('\\',"")

def remove_tab2(text):
    return re.sub('\s+',' ',text)

def remove_rt(text):
    return text.replace('RT'," ")

def remove_mention(text):
    return ' '.join(re.sub("([@#][A-Za-z0-9]+)|(\w+:\/\/\S+)"," ", text).split())

def remove_incomplete_url(text):
    return text.replace("http://", " ").replace("https://", " ")

def remove_single_char(text):
    return re.sub(r"\b[a-zA-Z]\b", "", text)

def remove_excessive_dot(text):
    return text.replace('..'," ")

def change_stripe(text):
    return text.replace('-'," ")

def lower(text):
    return text.lower()

def remove_single_char(text):
    return re.sub(r"\b[a-zA-Z]\b", "", text)

def remove_excessive_dot(text):
    return text.replace('..'," ")

def lower(text):
    return text.lower()

def remove_whitespace_LT(text):
    return text.strip()

def remove_whitespace_multiple(text):
    return re.sub('\s+',' ',text)

def remove_punctuation(text):
    remove = string.punctuation
    remove = remove.replace("_", "") # don't remove hyphens
    pattern = r"[{}]".format(remove) # create the pattern
    return re.sub(pattern, "", text)

In [57]:
# hapus untuk <>
def remove_number_eks(text):
    return text.replace('<number>'," ")

def remove_angka(text):
    return re.sub(r"\d+", "", text) 

def remove_URL_eks(text):
    return text.replace('URL'," ").replace('url'," ")

def space_punctuation(text):
    return re.sub('(?<! )(?=[.,!?()])|(?<=[.,!?()])(?! )', r' ', text)

In [60]:
i = 0
final_string = []
s = ""
for text in df['Text Tweet'].values:
    filteredSentence = []
    EachReviewText = ""
    proc = remove_rt(text)
    proc = lower(proc)
    proc = change_stripe(proc)
    proc = remove_emoji_alzami(proc)
    proc = remove_tab(proc)
    proc = remove_tab2(proc)
    proc = non_ascii(proc)
    proc = remove_incomplete_url(proc)
    proc = remove_excessive_dot(proc)
    proc = remove_whitespace_LT(proc)
    proc = remove_whitespace_multiple(proc)
    proc = remove_single_char(proc)
    proc = space_punctuation(proc)
    proc = remove_punctuation(proc)
    proc = remove_space_alzami(proc)
    proc = bersih_data(proc)
    proc = remove_number_eks(proc)
    proc = remove_angka(proc) 
    proc = remove_URL_eks(proc)
    EachReviewText = proc
    final_string.append(EachReviewText)

In [61]:
df["step01"] = final_string

In [62]:
df.head(10)

,Sentiment,Text Tweet,step01
0,negative,Jelek filmnya... apalagi si ernest gak mutu bg...,jelek filmnya apalagi si ernest gak mutu bgt a...
1,negative,Film king Arthur ini film paling jelek dari se...,film king arthur ini film paling jelek dari se...
2,negative,@beexkuanlin Sepanjang film gwa berkata kasar ...,bee sepanjang film gwa berkata kasar terus pad...
3,negative,Ane ga suka fast and furious..menurutku kok je...,ane ga suka fast and furious menurutku kok jel...
4,negative,"@baekhyun36 kan gua ga tau film nya, lu bilang...",baekhyun kan gua ga tau film nya lu bilang per...
5,negative,tolong editingnya yg bagus ya. Saya sering kec...,tolong editingnya yg bagus ya saya sering kece...
6,negative,Kecewa dgn salah satu aktornya yg ternyata pen...,kecewa dgn salah satu aktornya yg ternyata pen...
7,negative,Kecewa parah sama film the guys. Dear @raditya...,kecewa parah sama film the guys dear radityadi...
8,negative,Banyak yg kecewa abis nonton film ini :(,banyak yg kecewa abis nonton film ini
9,negative,#TheMummy 2017 adalah film yang paling memgece...,adalah film yang paling memgecewakan saya se...

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Sentiment   200 non-null    object
 1   Text Tweet  200 non-null    object
 2   step01      200 non-null    object
dtypes: object(3)
memory usage: 4.8+ KB

In [64]:
df_hapus = df[~df['step01'].str.contains(" ")]

In [65]:
df_hapus.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Sentiment   0 non-null      object
 1   Text Tweet  0 non-null      object
 2   step01      0 non-null      object
dtypes: object(3)
memory usage: 0.0+ bytes

In [66]:
df_hapus.head(10)

Empty DataFrame
Columns: [Sentiment, Text Tweet, step01]
Index: []

In [67]:
df_new = df[~df.isin(df_hapus)].dropna()

In [68]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Sentiment   200 non-null    object
 1   Text Tweet  200 non-null    object
 2   step01      200 non-null    object
dtypes: object(3)
memory usage: 4.8+ KB

In [69]:
df_new

,Sentiment,Text Tweet,step01
0,negative,Jelek filmnya... apalagi si ernest gak mutu bg...,jelek filmnya apalagi si ernest gak mutu bgt a...
1,negative,Film king Arthur ini film paling jelek dari se...,film king arthur ini film paling jelek dari se...
2,negative,@beexkuanlin Sepanjang film gwa berkata kasar ...,bee sepanjang film gwa berkata kasar terus pad...
3,negative,Ane ga suka fast and furious..menurutku kok je...,ane ga suka fast and furious menurutku kok jel...
4,negative,"@baekhyun36 kan gua ga tau film nya, lu bilang...",baekhyun kan gua ga tau film nya lu bilang per...
...,...,...,...
195,positive,Fargo juga adaptasi dari film yang cukup berha...,fargo juga adaptasi dari film yang cukup berha...
196,positive,637.000 waw ini sangat keren flm horor dng jum...,waw ini sangat keren flm horor dng jumlah ...
197,positive,@filmziarah film yang tenang dan menghanyutkan...,filmziarah film yang tenang dan menghanyutkan ...
198,positive,Film yg amat menarik. Kisah cinta & kesetiaan ...,film yg amat menarik kisah cinta kesetiaan yg ...
199,positive,"Nntn @filmziarah , film bagus, ada kali 5 meni...",nntn filmziarah film bagus ada kali menit pe...

In [73]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\user\anaconda3\lib\site-packages (3.7)
Requirement already satisfied: tqdm in c:\users\user\anaconda3\lib\site-packages (from nltk) (4.64.1)
Requirement already satisfied: click in c:\users\user\anaconda3\lib\site-packages (from nltk) (8.0.4)
Requirement already satisfied: joblib in c:\users\user\anaconda3\lib\site-packages (from nltk) (1.1.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\user\anaconda3\lib\site-packages (from nltk) (2022.7.9)
Requirement already satisfied: colorama in c:\users\user\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [77]:
# token
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

In [78]:
def word_tokenize_wrapper(text):
  return word_tokenize(text)

In [79]:
df_new['tokens'] = df['step01'].apply(word_tokenize_wrapper)

In [80]:
df_new.head(10)

,Sentiment,Text Tweet,step01,tokens
0,negative,Jelek filmnya... apalagi si ernest gak mutu bg...,jelek filmnya apalagi si ernest gak mutu bgt a...,"[jelek, filmnya, apalagi, si, ernest, gak, mut..."
1,negative,Film king Arthur ini film paling jelek dari se...,film king arthur ini film paling jelek dari se...,"[film, king, arthur, ini, film, paling, jelek,..."
2,negative,@beexkuanlin Sepanjang film gwa berkata kasar ...,bee sepanjang film gwa berkata kasar terus pad...,"[bee, sepanjang, film, gwa, berkata, kasar, te..."
3,negative,Ane ga suka fast and furious..menurutku kok je...,ane ga suka fast and furious menurutku kok jel...,"[ane, ga, suka, fast, and, furious, menurutku,..."
4,negative,"@baekhyun36 kan gua ga tau film nya, lu bilang...",baekhyun kan gua ga tau film nya lu bilang per...,"[baekhyun, kan, gua, ga, tau, film, nya, lu, b..."
5,negative,tolong editingnya yg bagus ya. Saya sering kec...,tolong editingnya yg bagus ya saya sering kece...,"[tolong, editingnya, yg, bagus, ya, saya, seri..."
6,negative,Kecewa dgn salah satu aktornya yg ternyata pen...,kecewa dgn salah satu aktornya yg ternyata pen...,"[kecewa, dgn, salah, satu, aktornya, yg, terny..."
7,negative,Kecewa parah sama film the guys. Dear @raditya...,kecewa parah sama film the guys dear radityadi...,"[kecewa, parah, sama, film, the, guys, dear, r..."
8,negative,Banyak yg kecewa abis nonton film ini :(,banyak yg kecewa abis nonton film ini,"[banyak, yg, kecewa, abis, nonton, film, ini]"
9,negative,#TheMummy 2017 adalah film yang paling memgece...,adalah film yang paling memgecewakan saya se...,"[adalah, film, yang, paling, memgecewakan, say..."

In [82]:
normalized_word = pd.read_csv('kamus_clean.csv')

In [83]:
normalized_word_dict = {}

for index, row in normalized_word.iterrows():
    if row[0] not in normalized_word_dict:
        normalized_word_dict[row[0]] = row[1] 

def normalized_term(document):
    return [normalized_word_dict[term] if term in normalized_word_dict else term for term in document]

In [84]:
df_new['final_tokens'] = df_new['tokens'].apply(normalized_term)

In [85]:
i=0
final_string_tokens = []
for text in df_new['final_tokens'].values:
    EachReviewText = ""
    EachReviewText = ' '.join(text)
    final_string_tokens.append(EachReviewText)

In [86]:
df_new["step02"] = final_string_tokens

In [87]:
df_new.head(10)

,Sentiment,Text Tweet,step01,tokens,final_tokens,step02
0,negative,Jelek filmnya... apalagi si ernest gak mutu bg...,jelek filmnya apalagi si ernest gak mutu bgt a...,"[jelek, filmnya, apalagi, si, ernest, gak, mut...","[jelek, filmnya, apalagi, si, ernest, gak, mut...",jelek filmnya apalagi si ernest gak mutu bgt a...
1,negative,Film king Arthur ini film paling jelek dari se...,film king arthur ini film paling jelek dari se...,"[film, king, arthur, ini, film, paling, jelek,...","[film, king, arthur, ini, film, paling, jelek,...",film king arthur ini film paling jelek dari se...
2,negative,@beexkuanlin Sepanjang film gwa berkata kasar ...,bee sepanjang film gwa berkata kasar terus pad...,"[bee, sepanjang, film, gwa, berkata, kasar, te...","[bee, sepanjang, film, gwa, berkata, kasar, te...",bee sepanjang film gwa berkata kasar terus pad...
3,negative,Ane ga suka fast and furious..menurutku kok je...,ane ga suka fast and furious menurutku kok jel...,"[ane, ga, suka, fast, and, furious, menurutku,...","[ane, ga, suka, fast, and, furious, menurutku,...",ane ga suka fast and furious menurutku kok jel...
4,negative,"@baekhyun36 kan gua ga tau film nya, lu bilang...",baekhyun kan gua ga tau film nya lu bilang per...,"[baekhyun, kan, gua, ga, tau, film, nya, lu, b...","[baekhyun, kan, gua, ga, tau, film, nya, lu, b...",baekhyun kan gua ga tau film nya lu bilang per...
5,negative,tolong editingnya yg bagus ya. Saya sering kec...,tolong editingnya yg bagus ya saya sering kece...,"[tolong, editingnya, yg, bagus, ya, saya, seri...","[tolong, editingnya, yg, bagus, ya, saya, seri...",tolong editingnya yg bagus ya saya sering kece...
6,negative,Kecewa dgn salah satu aktornya yg ternyata pen...,kecewa dgn salah satu aktornya yg ternyata pen...,"[kecewa, dgn, salah, satu, aktornya, yg, terny...","[kecewa, dgn, salah, satu, aktornya, yg, terny...",kecewa dgn salah satu aktornya yg ternyata pen...
7,negative,Kecewa parah sama film the guys. Dear @raditya...,kecewa parah sama film the guys dear radityadi...,"[kecewa, parah, sama, film, the, guys, dear, r...","[kecewa, parah, sama, film, the, guys, dear, r...",kecewa parah sama film the guys dear radityadi...
8,negative,Banyak yg kecewa abis nonton film ini :(,banyak yg kecewa abis nonton film ini,"[banyak, yg, kecewa, abis, nonton, film, ini]","[banyak, yg, kecewa, abis, nonton, film, ini]",banyak yg kecewa abis nonton film ini
9,negative,#TheMummy 2017 adalah film yang paling memgece...,adalah film yang paling memgecewakan saya se...,"[adalah, film, yang, paling, memgecewakan, say...","[adalah, film, yang, paling, memgecewakan, say...",adalah film yang paling memgecewakan saya sela...

In [88]:
df_new.to_csv('sentimen_film_clean_dataset.csv',sep=";")